Optimize app file watching to exclude git and node_module dirs
noop-cloud/noop-discovery pull request #6
Opened 2020-08-20 21:01 UTC by derekwolpert

2020-08-25 22:09 UTC, derekwolpert commented
@arbitrarytech @mwkaufman 

Added support for `version` settings values for PostgreSQL and MySQL resources based on those supported by [AWS RDS Aurora](https://aws.amazon.com/rds/aurora/faqs/#General).

Added GitHub Action to manage NPM releases. **Requires `NPM_TOKEN` secret value to be set on repo in order to function properly.** GitHub Action is triggered by running the [`npm version`](https://docs.npmjs.com/cli/version) command locally.

Will circle back and open up a separate PR to address file watching.

2020-09-02 14:12 UTC, mwkaufman commented
This should help with https://github.com/noop-cloud/noop-local/issues/54

2020-09-09 20:48 UTC, arbitrarytech requested changes

2020-09-09 20:48 UTC, arbitrarytech commented on lib/app.js
> +            if (fs.statSync(dir + '/' + file).isDirectory()) {
We should not be using any synchronous fs methods. While they won't cause any issue while noop-discovery is running in noop-local, it will cause unacceptable blocking on noop-control.

2020-09-09 20:48 UTC, arbitrarytech commented on lib/app.js
> +  parseManifest (file, done) {
This method seems like a duplication of what is done in `lib/manifest.js`. Why do it differently and duplicate the logic of parsing Noopfiles here?

2020-09-09 20:48 UTC, arbitrarytech commented on lib/manifest.js
> +        if (directive.cmd === 'COMPONENT' && sectionDirectives.length) {
Any particular reason for these changes? I know it's unnecessarily complicated as the only type of section we support right now is a `COMPONENT`, but there could be other section types in the future. This is a vestige of when we had separate directives for `SERVICE`, `FUNCTION`, `TASK`. and `STATIC`. While those have all been collapsed into the `COMPONENT` directive now, I could see some interesting uses for additional sections on the horizon.

2020-09-10 20:39 UTC, merged